server:
  cors_allow_origin:
    - "https://salvo.rs"

database: {}

jwt:
  jwt_exp: 6000

log:
  filter_level: "info"        # Available options: "debug", "info", "warn", "error"
  with_ansi: true
  to_stdout: true
  directory: "./logs"
  file_name: "my-service.log"
  rolling: "daily"            # Available options: "minutely", "hourly", "daily", "never"
